### ISSUE TITLE
[CY-6602] StandardRB (for Rubocop) Support?

### ISSUE THREAD

**Issue by berniechiu** [codacy/codacy-rubocop#404]
Hi Codacy Team,

Thanks for the nice platform.

https://github.com/codacy/codacy-rubocop/blob/99f23213f38d273856788b3ca4841098c5345e78/Gemfile#L20-L28

Could we add `standardrb` in `Gemfile` so that we could include it in the standard Rubocop YAML `.rubocop.yml` like:

```yaml
#=> .rubocop.yml
require: standard

inherit_gem:
  standard: config/base.yml
```

REF: https://github.com/testdouble/standard#usage-via-rubocop

Thanks a lot!

**Comment by DMarinhoCodacy** [comment]
Hello @berniechiu 
We already added the Standard gem.
Thanks,
David Marinho

**Comment by berniechiu** [comment]
Hi @DMarinhoCodacy, it still doesn't work at the moment?

![Codacy Rubocop Error](https://github.com/codacy/codacy-rubocop/assets/2749593/a80a7afc-4c42-4192-9306-4f3d80b00e9d)

**Comment by DMarinhoCodacy** [comment]
Hey @berniechiu 
What is the name of the repository?

**Comment by berniechiu** [comment]
Hi @DMarinhoCodacy, this is our private repository. However, if I have some free time in the next few days, I'll set up a public repository.

In the meantime, you're welcome to set up Rubocop from your team for testing.

Our config is fairly simple TBH

```yml
require:
  - rubocop-performance
  - rubocop-rails
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  # Prevent RuboCop from exploding when it finds an older-than-3.0 .ruby-version
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude: []
```
